### PR TITLE
Milestone 3

### PR DESCRIPTION
**Pull request by helman101**
## Milestone 3: Friendships v2 
- Refactor Friendship:
  - Controllers
  - Helpers
  - Tests
- Add more tests

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required :pray:
Nice work on this milestone @helman101 . 
This PR appears as re-review. So where are the changes requested by the previous reviewer? Did you create a new PR? If so, you are not supposed to do that. 

The previous reviews are needed for reference. I am currently confused because I don't see the changes requested previously.
Let's however make the following changes:
- [x] remove comments on lines 2-3 from the `user` model.
- [x] UsersController#index displays all users with `Friend Request` button next to users who are not their friends already.
- [x] Add `confirmed_friend` method to the `Friendship` model. This will help you to use SQL queries to process objects instead of processing objects in app memory
```ruby
def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
- [x] Now in the user model:
```ruby
has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
- [x] Add test cases for the models and the controllers. Read more about testing [here](https://guides.rubyonrails.org/testing.html)


### Martin Afani

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @helman101**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] make sure that all of your tests pass.


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Great job so far, 
Excellent use of shoulda-matchers in testing active record associations 👏 

#### Your integration specs seems to be failing
Screen Shot 2021-02-19 at 6 31 49 PM

#### The problem stems from Selenium::WebDriver. If there is a special configuration for this, kindly share in your readme file on how to setup your app for tests.
Screen Shot 2021-02-19 at 6 33 07 PM


### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by rindrajosia — APPROVED** [review]
**APPROVED**
Great work implementing the suggested changes, Congrats, the project is approved.
You may merge!
Rindra Josia

Keep up the good work

**Pull request merged**
